export const STRINGS = {
	TITLE_EDIT: 'Edit User',
	TITLE_CREATE: 'Create User',
	FIRST_NAME: 'First Name',
	FIRST_NAME_REQ: 'First name is required',
	LAST_NAME: 'Last Name',
	LAST_NAME_REQ: 'Last name is required',
	EMAIL: 'Email',
	EMAIL_REQ: 'Email is required',
	PASSWORD: 'Password',
	PASSWORD_REQ: 'Password is required',
	ROLE: 'Role',
	ROLE_REQ: 'Role is required',
	SELECT_ROLE: 'Select role',
	PHONE_NUMBER: 'Phone Number',
	DEPARTMENTS: 'Departments',
	BTN_CANCEL: 'Cancel',
	BTN_UPDATE: 'Update',
	BTN_CREATE: 'Create',
	LOADING: 'Loading departments...',
	ERROR: 'Error loading departments.',
};
