export const title = 'Dashboard';
export const totalEvents = 'Total Events';
export const activeEvents = 'Active Events';
export const criticalEvents = 'Critical Events';
export const highPriority = 'High Priority';
export const recentEvents = 'Recent Events';
export const recentStatusUpdates = 'Recent Status Updates';
export const statusUpdate = 'Status Update';
export const noNotes = 'No notes';
export const loadingEvents = 'Loading events...';
export const loadingStatus = 'Loading status...';
export const errorEvents = 'Error loading events.';
export const errorStatus = 'Error loading status updates.';
export const responderStatus = 'Responder Status';
export const activeEventsContext = (n: number) => `Across ${n} active event${n !== 1 ? 's' : ''}`;
export const noActiveEvents = 'No active events';
export const safe = 'Safe';
export const needHelp = 'Need Help';
export const away = 'Away';
export const unknown = 'Unknown';
export const totalResponders = (n: number) => `${n} responder${n !== 1 ? 's' : ''} reported`;
