export const eventDetails = 'Event Details';
export const description = 'Description';
export const noDescription = 'No description was provided for this event.';
export const startedAt = 'Started';
export const resolvedAt = 'Resolved';
export const reportedBy = 'Reported by';
export const location = 'Location';
export const departments = 'Departments';
export const noDepartments = 'No departments linked';
export const unknownReporter = 'Unknown';
export const attendants = 'Attendants';
export const attendantsHint = 'People from the departments linked to this event';
export const noAttendants = 'No attendants are linked to this event.';
export const noAttendantsForFilter = 'No attendants with this status.';
export const attendantsCount = (n: number) => `${n} ${n === 1 ? 'person' : 'people'}`;
export const filterAll = 'All';
export const reportedAt = (value: string) => `Reported ${value}`;
export const neverReported = 'Never reported';
export const close = 'Close';
export const loading = 'Loading event…';
export const notFound = 'This event is no longer available.';
export const reportedShare = (reported: number, total: number) => `${reported} of ${total} reported`;
