export const pageTitle = 'Shelters Map';
export const pageSubtitle = 'מקלטים בישראל · Public shelters in Israel';
export const loading = 'Loading shelters from OpenStreetMap...';
export const error = 'Failed to load shelter data. Please try again later.';
export const shelterCount = (n: number) => `${n.toLocaleString()} shelters found`;
export const attribution =
	'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors';
export const noAddress = 'No address on record';
export const findNearest = 'Find Nearest Shelter';
export const locating = 'Locating…';
export const nearestShelterLabel = 'Nearest Shelter';
export const distanceAway = (d: string) => `${d} away`;
export const locationDenied = 'Location access was denied. Please allow it in your browser settings.';
export const locationUnavailable = 'Could not determine your location. Try again.';
export const noSheltersLoaded = 'Shelters are still loading — try again in a moment.';
export const getDirections = 'Open Route in Google Maps';
export const fetchingAddress = 'Looking up address…';
export const addressUnavailable = 'No address on record';
export const departmentFilterLabel = 'My departments:';
export const addShelter = 'Add Shelter';
export const drawingTitle = 'Drawing a shelter';
export const drawingHint = 'Tap the map to outline the shelter area';
export const drawingPoints = (n: number) => `${n} / 3 points`;
export const drawingReady = (n: number) => `${n} points`;
export const undoPoint = 'Undo';
export const clearPoints = 'Clear';
export const cancelDrawing = 'Cancel';
export const finishDrawing = 'Save area';
export const departmentShelterBadge = 'Department shelter';
export const capacityLabel = (n: number) => `Holds ${n} people`;
export const deleteShelter = 'Delete shelter';
export const deleteShelterConfirm = 'Delete this shelter?';
export const deleteShelterMessage = (name: string) => `"${name}" will be removed from the department map.`;
