export const STRINGS = {
	login: 'login' as const,
	register: 'register' as const,
	email: 'Email',
	password: 'Password',
	firstName: 'First name',
	lastName: 'Last name',
	confirmPassword: 'Confirm password',
	title: 'EmergenSee',
	subtitle: 'Emergency Response System',
	orEmail: 'or use email',
	loggingIn: 'Logging in...',
	logIn: 'Log in',
	dontHaveAccount: "Don't have an account? ",
	registerBtn: 'Register',
	creatingAccount: 'Creating account...',
	createAccount: 'Create account',
	alreadyHaveAccount: 'Already have an account? ',
	passwordsDoNotMatch: 'Passwords do not match',
	min8Chars: '(min. 8 characters)',
	emailRequired: 'Email is required',
	passwordRequired: 'Password is required',
	firstNameRequired: 'Required',
	lastNameRequired: 'Required',
	passwordConfirmRequired: 'Please confirm your password',
	min8CharsMessage: 'Minimum 8 characters',
	googleSignInFailed: 'Google sign-in failed. Please try again.',
	loginFailed: 'Login failed. Please try again.',
	registrationFailed: 'Registration failed. Please try again.',
};
