export const editDepartment = 'Edit Department';
export const createDepartment = 'Create Department';
export const nameLabel = 'Name';
export const descriptionLabel = 'Description';
export const subDepartmentsLabel = 'Sub Departments (Hold Ctrl/Cmd to select multiple)';
export const savingText = 'Saving...';
export const saveText = 'Save';
export const cancelText = 'Cancel';
export const defaultError = 'An error occurred';
