export const pageTitle = 'Departments';
export const searchPlaceholder = 'Search departments...';
export const createButton = 'Create Department';
export const loading = 'Loading departments...';
export const error = 'Failed to load departments.';
export const noDepartments = 'No departments found.';
export const confirmDelete = 'Are you sure you want to delete this department?';
export const noAdmins = 'No Admins';
export const unknownAdmin = 'Unknown';
