export const EventFormStrings = {
	TITLE_EDIT: 'Edit Event',
	TITLE_CREATE: 'Create Event',
	LABEL_TITLE: 'Title',
	LABEL_TYPE: 'Type',
	LABEL_PRIORITY: 'Priority',
	LABEL_DEPARTMENTS: 'Departments (Hold Ctrl/Cmd to select multiple)',
	LABEL_DESCRIPTION: 'Description',
	BTN_CANCEL: 'Cancel',
	BTN_UPDATE: 'Update',
	BTN_CREATE: 'Create',
	PLACEHOLDER_SELECT_TYPE: 'Select type',
	PLACEHOLDER_SELECT_PRIORITY: 'Select priority',
	ERR_TITLE_REQUIRED: 'Title is required',
	ERR_TYPE_REQUIRED: 'Type is required',
	ERR_PRIORITY_REQUIRED: 'Priority is required',
	ERR_DEPARTMENTS_REQUIRED: 'At least one department is required',
	ERR_DESCRIPTION_REQUIRED: 'Description is required',
	LOADING_DEPARTMENTS: 'Loading departments...',
	ERROR_DEPARTMENTS: 'Error loading departments!',
};
