import {
	FaChartBar,
	FaExclamationCircle,
	FaMap,
	FaUsers,
	FaBuilding,
	FaMapMarkerAlt,
	FaHeartbeat,
	FaChevronLeft,
	FaChevronRight,
	FaSignOutAlt,
} from 'react-icons/fa';

export const CONSTS = {
	ROUTES: {
		DASHBOARD: '/dashboard',
		EVENTS: '/events',
		MAP: '/map',
		USERS: '/users',
		DEPARTMENTS: '/departments',
		STATUS: '/status',
		EMERGENCY_REPORT: '/emergency-report',
		PROFILE: '/profile',
	},
	QUERY_KEYS: {
		EVENTS: ['events'] as const,
		STATUS: ['status'] as const,
	},
	ICONS: {
		DASHBOARD: FaChartBar,
		EVENTS: FaExclamationCircle,
		MAP: FaMap,
		USERS: FaUsers,
		DEPARTMENTS: FaBuilding,
		STATUS: FaMapMarkerAlt,
		EMERGENCY: FaHeartbeat,
		COLLAPSE: FaChevronLeft,
		EXPAND: FaChevronRight,
		LOGOUT: FaSignOutAlt,
	},
	CLASSES: {
		SIDEBAR_BASE: 'relative bg-white shadow-lg transition-all duration-200',
		SIDEBAR_EXPANDED: 'w-64',
		SIDEBAR_COLLAPSED: 'w-20',
		SIDEBAR_BTN:
			'absolute -right-3 top-8 z-10 h-6 w-6 rounded-full border border-gray-200 bg-white text-gray-600 shadow-sm hover:bg-gray-50 flex items-center justify-center text-xs',
		LAYOUT_CONTAINER: 'flex h-screen bg-gray-100',
		SIDEBAR_WRAPPER: 'flex flex-col h-full',
		LOGO_CONTAINER_BASE: 'py-4 border-b border-gray-200',
		LOGO_CONTAINER_EXPANDED: 'px-6',
		LOGO_CONTAINER_COLLAPSED: 'px-3 text-center',
		LOGO_TEXT_EXPANDED: 'text-2xl font-bold text-blue-600',
		LOGO_TEXT_COLLAPSED: 'text-2xl font-bold text-blue-600',
		SUBTITLE: 'text-xs text-gray-600 mt-1',
		NAV_CONTAINER_BASE: 'flex-1 py-4 space-y-1',
		NAV_CONTAINER_EXPANDED: 'px-4',
		NAV_CONTAINER_COLLAPSED: 'px-2',
		NAV_LINK_BASE: 'flex items-center px-4 py-3 text-sm font-medium rounded-lg transition-colors',
		NAV_LINK_COLLAPSED_EXTRA: 'justify-center px-2',
		EMERGENCY_MSG_ACTIVE: 'bg-red-600 text-white',
		EMERGENCY_MSG_INACTIVE: 'bg-red-500 text-white hover:bg-red-600 shadow-md',
		EMERGENCY_PULSE: 'animate-pulse',
		NORMAL_MSG_ACTIVE: 'bg-blue-50 text-blue-700',
		NORMAL_MSG_INACTIVE: 'text-gray-700 hover:bg-gray-50',
		USER_INFO_CONTAINER_BASE: 'px-4 py-4 border-t border-gray-200',
		USER_INFO_CONTAINER_COLLAPSED: 'text-center',
		USER_BTN_BASE: 'block w-full text-left hover:bg-gray-50 rounded-lg',
		USER_BTN_EXPANDED_EXTRA: 'p-2 -mx-2',
		USER_FLEX: 'flex items-center',
		USER_DETAILS: 'flex-1',
		USER_NAME_TEXT: 'text-sm font-medium text-gray-900',
		USER_EMAIL_TEXT: 'text-xs text-gray-600 truncate',
		USER_AVATAR:
			'mx-auto mb-2 flex h-8 w-8 items-center justify-center rounded-full bg-blue-50 text-xs font-semibold text-blue-700 hover:bg-blue-100',
		LOGOUT_BTN_BASE:
			'mt-3 flex items-center justify-center w-full text-sm font-medium text-gray-700 bg-gray-100 rounded-lg hover:bg-gray-200 transition-colors',
		LOGOUT_BTN_EXPANDED: 'px-4 py-2 gap-2',
		LOGOUT_BTN_COLLAPSED: 'px-2 py-2',
		MAIN_CONTENT: 'flex-1 overflow-auto',
	},
};
